services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: worker
    name: client-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bots/client_bot.py

  - type: worker
    name: admin-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bots/admin_bot.py
